### ISSUE TITLE
Failed to load the game

### ISSUE THREAD

**Issue by laenion** [tonihele/OpenKeeper#251]
I've tried running the German disc version of Dungeon Keeper II on Linux, but the game fails to start. A splash screen can be seen for a fraction of a second, then the game quits, leaving the following console output:

```
user@pegasus6:~/OpenKeeper$ gradle run
Incremental java compilation is an incubating feature.
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
Okt 09, 2016 9:19:37 PM com.jme3.system.JmeDesktopSystem initialize
INFORMATION: Running on jMonkeyEngine 3.1-beta1
 * Branch: HEAD
 * Git Hash: 310f4db
 * Build Date: 2016-04-25
Okt 09, 2016 9:19:37 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFORMATION: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
Okt 09, 2016 9:19:37 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFORMATION: OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GTX 960/PCIe/SSE2
 * OpenGL Version: 4.5.0 NVIDIA 367.35
 * GLSL Version: 4.50 NVIDIA
 * Profile: Compatibility
Okt 09, 2016 9:19:37 PM com.jme3.asset.AssetConfig loadText
WARNUNG: Cannot find loader com.jme3.audio.plugins.OGGLoader
Okt 09, 2016 9:19:38 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMATION: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
Okt 09, 2016 9:19:38 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNUNG: Pausing audio device not supported.
Okt 09, 2016 9:19:38 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMATION: Audio effect extension version: 1.0
Okt 09, 2016 9:19:38 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMATION: Audio max auxiliary sends: 4
Okt 09, 2016 9:19:38 PM de.lessvoid.nifty.render.batch.BatchRenderDevice createTextureAtlas
INFORMATION: Created a new texture atlas (atlas texture id: 1).
Okt 09, 2016 9:19:38 PM de.lessvoid.nifty.render.batch.BatchRenderDevice nextTextureAtlas
INFORMATION: Switched atlases to atlas texture with id: 1.
Okt 09, 2016 9:19:38 PM com.jme3.export.binary.BinaryInputCapsule readString
WARNUNG: Your export has been saved with an incorrect encoding for it's String fields which means it might not load correctly due to encoding issues. You should probably re-export your work. See ISSUE 276 in the jME issue tracker.
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.map.KwdFile readMapInfo
INFORMATION: Reading level info!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.tools.convert.ConversionUtils parseEnum
WARNUNG: Value 1.635.017.028 not specified for enum class toniarts.openkeeper.tools.convert.map.MapDataTypeEnum!
Okt 09, 2016 9:19:38 PM toniarts.openkeeper.Main$5 onLoad
SCHWERWIEGEND: Failed to load the game!
java.lang.RuntimeException: Failed to read the file /home/user/DKII/Data/editor/maps/FrontEnd3DLevel.kwd!
        at toniarts.openkeeper.tools.convert.map.KwdFile.<init>(KwdFile.java:147)
        at toniarts.openkeeper.tools.convert.map.KwdFile.<init>(KwdFile.java:128)
        at toniarts.openkeeper.game.state.MainMenuState.loadMenuScene(MainMenuState.java:127)
        at toniarts.openkeeper.game.state.MainMenuState.<init>(MainMenuState.java:114)
        at toniarts.openkeeper.Main$5.onLoad(Main.java:370)
        at toniarts.openkeeper.game.state.loading.LoadingState$1.call(LoadingState.java:143)
        at toniarts.openkeeper.game.state.loading.LoadingState$1.call(LoadingState.java:140)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -4
        at java.lang.String.substring(String.java:1960)
        at toniarts.openkeeper.tools.convert.map.KwdFile.readMapInfo(KwdFile.java:1107)
        at toniarts.openkeeper.tools.convert.map.KwdFile.readFileContents(KwdFile.java:294)
        at toniarts.openkeeper.tools.convert.map.KwdFile.readFileContents(KwdFile.java:174)
        at toniarts.openkeeper.tools.convert.map.KwdFile.<init>(KwdFile.java:144)
        ... 10 more

Okt 09, 2016 9:19:38 PM com.jme3.app.LegacyApplication handleError
SCHWERWIEGEND: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.IllegalStateException: Shutdown in progress
        at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
        at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
        at org.lwjgl.opengl.Display$3.run(Display.java:712)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.lwjgl.opengl.Display.removeShutdownHook(Display.java:710)
        at org.lwjgl.opengl.Display.access$800(Display.java:65)
        at org.lwjgl.opengl.Display$5.destroy(Display.java:839)
        at org.lwjgl.opengl.Display.destroy(Display.java:1095)
        at com.jme3.system.lwjgl.LwjglDisplay.destroyContext(LwjglDisplay.java:158)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.deinitInThread(LwjglAbstractDisplay.java:196)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:237)
        at java.lang.Thread.run(Thread.java:745)

AL lib: (EE) alc_cleanup: 1 device not closed

BUILD SUCCESSFUL

Total time: 3.918 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html
```

Unfortunately there are several error messages in the above log ("Your export has been saved with an incorrect encoding [...]", "Failed to read the file /home/user/DKII/Data/editor/maps/FrontEnd3DLevel.kwd", "String index out of range: -4"), so I'm not sure where to start looking. I'm running the game using `gradle run`, both using the files directly from disc and from a local copy of the disc's content.

I'm not sure if it's relevant, but during the conversion progress dialogue on first start a lot of messages similar to the following were printed:

```
Okt 09, 2016 9:54:35 PM toniarts.openkeeper.utils.TangentBinormalGenerator processTriangleData
WARNUNG: Angle between tangents exceeds tolerance for vertex 73.
```

Occasionally also warnings similar to the following were to be seen:

```
WARNUNG: Shared tangent is zero for vertex 19.
WARNUNG: Colinear uv coordinates for triangle [19, 16, 18]; tex0 = [0,25, 0], tex1 = [0,5, 0], tex2 = [0, 0]
```

And similarily for the "music and sounds" file conversion:

```
WARNUNG: Value 3 not specified for enum class toniarts.openkeeper.tools.convert.sound.SdtFileEntry$SoundType!
```

**Comment by ufdada** [comment]
That's weird, it can't set the name. We only do that substring if the string ends with ".kwd", so it need to have at least 4 digits. This would only fail if the worst case scenario ".kwd" would be the whole string.
Can you check what value name has? (it's in KwdFile Line 1004)
Just put `System.out.println(name);` before that line

We should figure out what kind of sound file type 3 is. Maybe the file name gives us a hint.
Go to SdtFile.java on Line 79 (after setting the name) and put `System.out.println(entry.getName());` on the next line. Then you only need to delete the file `openkeeper.properties` to reconvert the assets.

**Comment by tonihele** [comment]
There is an empty file path. I guess it is possible, the main menu doesn't need i.e. creature record. Just haven't seen one, maybe some early version.

The tangent stuff is pretty normal.

**Comment by laenion** [comment]
@ufdada I guess you meant line 1107 in KwdFile - the last path is indeed empty.
This is the list of paths:
```
tor/Objectsx
tor/Rooms
tor/Creatures
tor/CreatureSpells
tor/Traps
tor/Doors
tor/Shots
tor/KeeperSpells
tor/Maps/FrontEnd3DLevelPlayers.kld
tor/Maps/FrontEnd3DLevelMap.kld
tor/Maps/FrontEnd3DLevelTriggers.kld
tor/GlobalVariables.kwd
tor/Maps/FrontEnd3DLevelVariables.kld
tor/Maps/FrontEnd3DLevelThings.kld

```

When inserting debug output in line 1004 the result is `S:\DK2\Level design\Front End\FrontEnd3DLevel.kwd`.

The following sound files were reported with a warning with one of the two file patterns:
```
lvlspe(01-60).wav
lvlspe(01-60).mp2
```
The source files were _speech_demo2HD.SDT_, _speech_secret2HD.SDT_, _speech_secret4HD.SDT_ and _speech_level6aHD.SDT_.

**Comment by tonihele** [comment]
https://github.com/tonihele/OpenKeeper/blob/master/src/toniarts/openkeeper/tools/convert/map/KwdFile.java#L263

^
Might actually be a version flag. There is a difference in file lengths. Same as the creatures record. Two possible file lengths seen.

**Comment by tonihele** [comment]
I've devised a fix that will allow to load these files up. Could you test this patch if it works for you? Try also few campaign maps and some skirmish levels. This doesn't at least break any patched version. If it works, I'll push it to the master.

[level.txt](https://github.com/tonihele/OpenKeeper/files/531134/level.txt)

**Comment by laenion** [comment]
Thanks a lot, the intro and main menu seem to be working as expected now (judging from the last OpenKeeper Youtube update video as I have never played the game before)! Now the game is crashing when trying to show the loading screen (either when "continuing" a campaign or starting a skirmish level:

```
Okt 15, 2016 5:18:38 PM com.jme3.app.LegacyApplication handleError
SCHWERWIEGEND: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetNotFoundException: Textures/LoadingScreen-Japanese/LoadingScreen1600x1200.png (Flipped)
        at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:370)
        at com.jme3.asset.DesktopAssetManager.loadTexture(DesktopAssetManager.java:390)
        at toniarts.openkeeper.game.state.loading.SingleBarLoadingState.getLoadingScreenTexture(SingleBarLoadingState.java:98)
        at toniarts.openkeeper.game.state.loading.LoadingState.setupTitleScreen(LoadingState.java:83)
        at toniarts.openkeeper.game.state.loading.LoadingState.initialize(LoadingState.java:70)
        at toniarts.openkeeper.game.state.loading.SingleBarLoadingState.initialize(SingleBarLoadingState.java:73)
        at com.jme3.app.state.AppStateManager.initializePending(AppStateManager.java:251)
        at com.jme3.app.state.AppStateManager.update(AppStateManager.java:281)
        at com.jme3.app.SimpleApplication.update(SimpleApplication.java:236)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
        at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by laenion** [comment]
I should probably add that renaming _Textures/LoadingScreen_ to _Textures/LoadingScreen-Japanese_ will fix this. The levels seem to load fine, though the camera seems to have problems during ingame cutscenes.

The question why the German version is looking for Japanese loading screens remains though...

**Comment by tonihele** [comment]
It is due to the WAD archives. For me the majority of the loading screens are in the Japanese folder, just one entry in the LoadingScreen folder. It maybe something that we don't fully understand about the archives.

There is this software called DragonUnpacker that reads those files as well, and it shows flatter directory structure (one file per dir) and we read the archive differently. But probably neither got it 100% right. Also it might be that they are not really meant for unpacking to a directory structure. I don't know.

Can you make a video to YouTube etc. for the camera? I don't know what we can do about that.

I'll at least patch in the fix for the level loading.

**Comment by tonihele** [comment]
Our WadFileEntry has that unknown value (unk1). If we would use it as a sort key... I wonder what kind of directory structure we would get... We preserve the last directory when extracting to get the structure.

**Comment by laenion** [comment]
I tried several times, but I can't reproduce the camera issues any more... The camera used to get stuck in the level or just showing a black screen at the end of ingame video cutscenes. I'll open another bug report if I should see this problem again.

**Comment by tonihele** [comment]
Okay, so it is quite normal then. It happens some times, I know what you mean. There is a concurrency issue in our cinematics that might be the cause, that is why it is so random.

**Comment by tonihele** [comment]
Getting nowhere with the WADs, no idea what to do about them. I would hate to see us falling back to a flat structure. Maybe somebody figures them out one day. At least the main issue is now sorted out. Better leave this one open for the sake of the WAD issue.

**Comment by ufdada** [comment]
> Our WadFileEntry has that unknown value (unk1). If we would use it as a sort key... I wonder what kind of directory structure we would get... We preserve the last directory when extracting to get the structure.

Looks like this value is some kind of index, at least it looks like your idea isn't too bad
![image](https://cloud.githubusercontent.com/assets/3787188/19416844/9228160e-939b-11e6-9d99-7568bb3c4a54.png)

**Comment by tonihele** [comment]
It didnt work. But it is no key either. There are some duplicates.

**Comment by ufdada** [comment]
Well maybe some kind of sequence? smaller has higher priority?

**Comment by tonihele** [comment]
Ok, there was this issue in the WAD extractor of ours.... You see, old versions don't have the Japanese loading screens and their WAD file gets extracted to \LoadingScreen\ correctly. Newer version contains both. And they are mirrored, we couldn't handle the same file names and actually the Japanese loading screens didn't really extract at all, but the English ones to the \LoadingScreen-Japanese\ which OpenKeeper used by default. This looked kinda funny but I never really dug the reason.

So now we successfully extract them all in their correct folders. And now we use the Japanese version if your locale is Japanese, otherwise English.
